[platformio]
default_envs = esp32dev

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.partitions = huge_app.csv
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -Wl,--wrap=ieee80211_raw_frame_sanity_check
lib_deps =
    olikraus/U8g2@^2.35.19
    lsatan/SmartRC-CC1101-Driver-Lib@^2.5.7
    sui77/rc-switch@^2.6.4
    ; Adafruit PN532 forked locally to lib/PN532Custom/ — adds AsTargetUID()
    adafruit/Adafruit BusIO@^1.16.1
    crankyoldgit/IRremoteESP8266@^2.8.6

[env:esp32dev]
build_src_filter =
    +<*>
    -<../test/*>

[env:cc1101_test]
build_src_filter =
    -<*>
    +<../test/test_cc1101.cpp>

[env:pn532_test]
build_src_filter =
    -<*>
    +<../test/test_pn532.cpp>

[env:wifi_lab_test]
build_src_filter =
    -<*>
    +<../test/test_wifi_lab.cpp>

[env:sd_test]
build_src_filter =
    -<*>
    +<../test/test_sd.cpp>

[env:ir_test]
build_src_filter =
    -<*>
    +<../test/test_ir.cpp>

[env:cc1101_dual_test]
build_src_filter =
    -<*>
    +<../test/test_cc1101_dual.cpp>

[env:deauth_test]
build_src_filter =
    -<*>
    +<../test/test_deauth.cpp>
